import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar'
import { Aladin } from "next/font/google" 

const aladin = Aladin({
    weight: ["400"],
    styles: ["italic", "normal"],
    subsets: ["latin"]
})

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={aladin.className}>
        <Navbar />{children}
      </body>
    </html>
  )
}
